# This is a basic workflow to help you get started with Actions
name: CICD

# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  
  AWS_REGION : "us-east-2" 


permissions:
      id-token: write  
      contents: read    
jobs:
  install-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipx
        pipx install poetry==1.4.2
        poetry install
    - name: Test with pytest
      run: |
        poetry run pytest
  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: install-and-test
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::199695711962:role/GitHubAction 
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        env: 
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_NAME: bingo-simulator
        run: |
          docker build -t bingo-simulator:latest .
          docker tag bingo-simulator:latest $ECR_REGISTRY/$ECR_REPOSITORY$IMAGE_NAME:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY$IMAGE_NAME:latest
